 RVBBIT_DIRECT_ACCEL_LOAD=1 \
 BENCH_LIMIT=100000 \
 BENCH_SYSTEMS=rvbbit \
  RVBBIT_DIRECT_ACCEL_METADATA_PROFILE=minimal \
  RVBBIT_REFRESH_LAYOUT_VARIANTS_AFTER_LOAD=async \
  RVBBIT_DIRECT_ACCEL_CHUNK_ROWS=25000 \
  RVBBIT_COMPACT_SCAN_CHUNK_ROWS=25000 \
  RVBBIT_COMPACT_WRITER_THREADS=4 \
  ./bench/clickbench/run_offline.sh --rebuild --reset-rvbbit-extension --test-name saturday_churn1
  
