LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/opt/rvbbit-samples/sales_history/costs.csv'
APPEND INTO TABLE SH.COSTS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  PROD_ID,
  TIME_ID DATE "YYYY-MM-DD",
  PROMO_ID,
  CHANNEL_ID,
  UNIT_COST,
  UNIT_PRICE
)
