LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/opt/rvbbit-samples/sales_history/customers.csv'
APPEND INTO TABLE SH.CUSTOMERS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CUST_ID,
  CUST_FIRST_NAME CHAR(20),
  CUST_LAST_NAME CHAR(40),
  CUST_GENDER CHAR(1),
  CUST_YEAR_OF_BIRTH,
  CUST_MARITAL_STATUS CHAR(20),
  CUST_STREET_ADDRESS CHAR(40),
  CUST_POSTAL_CODE CHAR(10),
  CUST_CITY CHAR(30),
  CUST_CITY_ID,
  CUST_STATE_PROVINCE CHAR(40),
  CUST_STATE_PROVINCE_ID,
  COUNTRY_ID,
  CUST_MAIN_PHONE_NUMBER CHAR(25),
  CUST_INCOME_LEVEL CHAR(30),
  CUST_CREDIT_LIMIT,
  CUST_EMAIL CHAR(50),
  CUST_TOTAL CHAR(14),
  CUST_TOTAL_ID,
  CUST_SRC_ID,
  CUST_EFF_FROM DATE "YYYY-MM-DD",
  CUST_EFF_TO DATE "YYYY-MM-DD",
  CUST_VALID CHAR(1)
)
