LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/opt/rvbbit-samples/sales_history/promotions.csv'
APPEND INTO TABLE SH.PROMOTIONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  PROMO_ID,
  PROMO_NAME CHAR(30),
  PROMO_SUBCATEGORY CHAR(30),
  PROMO_SUBCATEGORY_ID,
  PROMO_CATEGORY CHAR(30),
  PROMO_CATEGORY_ID,
  PROMO_COST,
  PROMO_BEGIN_DATE DATE "YYYY-MM-DD",
  PROMO_END_DATE DATE "YYYY-MM-DD",
  PROMO_TOTAL CHAR(15),
  PROMO_TOTAL_ID
)
