LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/opt/rvbbit-samples/sales_history/supplementary_demographics.csv'
APPEND INTO TABLE SH.SUPPLEMENTARY_DEMOGRAPHICS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CUST_ID,
  EDUCATION CHAR(21),
  OCCUPATION CHAR(21),
  HOUSEHOLD_SIZE CHAR(21),
  YRS_RESIDENCE,
  AFFINITY_CARD,
  CRICKET,
  BASEBALL,
  TENNIS,
  SOCCER,
  GOLF,
  UNKNOWN,
  MISC,
  COMMENTS CHAR(4000)
)
