LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/opt/rvbbit-samples/sales_history/times.csv'
APPEND INTO TABLE SH.TIMES
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  TIME_ID DATE "YYYY-MM-DD",
  DAY_NAME CHAR(9),
  DAY_NUMBER_IN_WEEK,
  DAY_NUMBER_IN_MONTH,
  CALENDAR_WEEK_NUMBER,
  FISCAL_WEEK_NUMBER,
  WEEK_ENDING_DAY DATE "YYYY-MM-DD",
  WEEK_ENDING_DAY_ID,
  CALENDAR_MONTH_NUMBER,
  FISCAL_MONTH_NUMBER,
  CALENDAR_MONTH_DESC CHAR(8),
  CALENDAR_MONTH_ID,
  FISCAL_MONTH_DESC CHAR(8),
  FISCAL_MONTH_ID,
  DAYS_IN_CAL_MONTH,
  DAYS_IN_FIS_MONTH,
  END_OF_CAL_MONTH DATE "YYYY-MM-DD",
  END_OF_FIS_MONTH DATE "YYYY-MM-DD",
  CALENDAR_MONTH_NAME CHAR(9),
  FISCAL_MONTH_NAME CHAR(9),
  CALENDAR_QUARTER_DESC CHAR(7),
  CALENDAR_QUARTER_ID,
  FISCAL_QUARTER_DESC CHAR(7),
  FISCAL_QUARTER_ID,
  DAYS_IN_CAL_QUARTER,
  DAYS_IN_FIS_QUARTER,
  END_OF_CAL_QUARTER DATE "YYYY-MM-DD",
  END_OF_FIS_QUARTER DATE "YYYY-MM-DD",
  CALENDAR_QUARTER_NUMBER,
  FISCAL_QUARTER_NUMBER,
  CALENDAR_YEAR,
  CALENDAR_YEAR_ID,
  FISCAL_YEAR,
  FISCAL_YEAR_ID,
  DAYS_IN_CAL_YEAR,
  DAYS_IN_FIS_YEAR,
  END_OF_CAL_YEAR DATE "YYYY-MM-DD",
  END_OF_FIS_YEAR DATE "YYYY-MM-DD"
)
