-- Upgrade pg_rvbbit 2.3.5 -> 2.3.6
--
-- AUTO-GENERATED STUB. Postgres needs this edge for ALTER EXTENSION UPDATE.
-- If this release changed the SQL surface (CREATE/ALTER TABLE/FUNCTION/VIEW,
-- new catalog columns, etc.), replace this comment with the upgrade DDL.
-- Verify with: make migration-check
