//! Stacked, idempotent, run-once SQL migrations — decoupled from the extension
//! version.
//!
//! Postgres's native `ALTER EXTENSION UPDATE FROM..TO` forces a contiguous
//! version-edge graph that we'd coupled to the docker release tag; it drifts and
//! breaks. Instead, every file in `sql/migrations/NNNN_*.sql` is applied in
//! order exactly once, tracked in `rvbbit.schema_migrations`, by
//! `rvbbit.migrate()` — "run whatever hasn't run yet", never by version. The
//! extension version now only governs the C/.so bindings.
//!
//! Adding a migration:
//!   1. drop `sql/migrations/NNNN_description.sql` (idempotent DDL: CREATE OR
//!      REPLACE / IF NOT EXISTS), NNNN strictly increasing;
//!   2. add one line to `MIGRATIONS` below;
//!   3. rebuild the image. Deploy runs `SELECT rvbbit.migrate();` (Makefile
//!      reload-extension / docker init), which applies the new one.
//!
//! Never reorder or edit an already-shipped migration's SQL — add a new one.

use pgrx::prelude::*;

/// Ordered, compile-time-embedded migration list. APPEND ONLY.
const MIGRATIONS: &[(&str, &str)] = &[
    (
        "0001_durable_catalog_crawl",
        include_str!("../sql/migrations/0001_durable_catalog_crawl.sql"),
    ),
    (
        "0002_default_embedder",
        include_str!("../sql/migrations/0002_default_embedder.sql"),
    ),
    (
        "0003_parallel_catalog_crawl",
        include_str!("../sql/migrations/0003_parallel_catalog_crawl.sql"),
    ),
    (
        "0004_cubes",
        include_str!("../sql/migrations/0004_cubes.sql"),
    ),
    (
        "0005_cubes_enrich",
        include_str!("../sql/migrations/0005_cubes_enrich.sql"),
    ),
    (
        "0006_cubes_v3",
        include_str!("../sql/migrations/0006_cubes_v3.sql"),
    ),
    (
        "0007_cubes_sql_trim",
        include_str!("../sql/migrations/0007_cubes_sql_trim.sql"),
    ),
    (
        "0008_proposals",
        include_str!("../sql/migrations/0008_proposals.sql"),
    ),
    (
        "0009_cube_model",
        include_str!("../sql/migrations/0009_cube_model.sql"),
    ),
    (
        "0010_metric_proposals",
        include_str!("../sql/migrations/0010_metric_proposals.sql"),
    ),
    (
        "0011_near_frontier_proposals",
        include_str!("../sql/migrations/0011_near_frontier_proposals.sql"),
    ),
    (
        "0012_semantic_model",
        include_str!("../sql/migrations/0012_semantic_model.sql"),
    ),
    (
        "0013_proposal_lifecycle",
        include_str!("../sql/migrations/0013_proposal_lifecycle.sql"),
    ),
    (
        "0014_materialize_all_metrics",
        include_str!("../sql/migrations/0014_materialize_all_metrics.sql"),
    ),
    (
        "0015_proposal_exemplars",
        include_str!("../sql/migrations/0015_proposal_exemplars.sql"),
    ),
    (
        "0016_activity_discovery",
        include_str!("../sql/migrations/0016_activity_discovery.sql"),
    ),
    (
        "0017_usage_weighted_search",
        include_str!("../sql/migrations/0017_usage_weighted_search.sql"),
    ),
    (
        "0018_proposal_quality",
        include_str!("../sql/migrations/0018_proposal_quality.sql"),
    ),
    (
        "0019_metric_check_resilience",
        include_str!("../sql/migrations/0019_metric_check_resilience.sql"),
    ),
    (
        "0020_proposal_categories",
        include_str!("../sql/migrations/0020_proposal_categories.sql"),
    ),
    (
        "0021_edit_primitives",
        include_str!("../sql/migrations/0021_edit_primitives.sql"),
    ),
    (
        "0022_cube_categories",
        include_str!("../sql/migrations/0022_cube_categories.sql"),
    ),
    (
        "0023_propose_column_profile",
        include_str!("../sql/migrations/0023_propose_column_profile.sql"),
    ),
    (
        "0024_metric_lineage_breaching",
        include_str!("../sql/migrations/0024_metric_lineage_breaching.sql"),
    ),
    (
        "0025_fk_inference",
        include_str!("../sql/migrations/0025_fk_inference.sql"),
    ),
    (
        "0026_refresh_all_cubes",
        include_str!("../sql/migrations/0026_refresh_all_cubes.sql"),
    ),
    (
        "0027_dimensional_metrics",
        include_str!("../sql/migrations/0027_dimensional_metrics.sql"),
    ),
    (
        "0028_drop_stale_overloads",
        include_str!("../sql/migrations/0028_drop_stale_overloads.sql"),
    ),
    (
        "0029_cube_refresh_pacing_and_accel_exclude",
        include_str!("../sql/migrations/0029_cube_refresh_pacing_and_accel_exclude.sql"),
    ),
    (
        "0030_fix_refresh_all_cubes_overload",
        include_str!("../sql/migrations/0030_fix_refresh_all_cubes_overload.sql"),
    ),
    (
        "0031_brain_phase0",
        include_str!("../sql/migrations/0031_brain_phase0.sql"),
    ),
    (
        "0032_batch_embed_crawl_prewarm",
        include_str!("../sql/migrations/0032_batch_embed_crawl_prewarm.sql"),
    ),
    (
        "0033_crawl_exclude_operational_schemas",
        include_str!("../sql/migrations/0033_crawl_exclude_operational_schemas.sql"),
    ),
    (
        "0034_brain_acl_management",
        include_str!("../sql/migrations/0034_brain_acl_management.sql"),
    ),
    (
        "0035_fast_fingerprint_materialize_sample",
        include_str!("../sql/migrations/0035_fast_fingerprint_materialize_sample.sql"),
    ),
    (
        "0036_fingerprint_reltuples_rowcount",
        include_str!("../sql/migrations/0036_fingerprint_reltuples_rowcount.sql"),
    ),
    (
        "0037_fingerprint_always_materialize",
        include_str!("../sql/migrations/0037_fingerprint_always_materialize.sql"),
    ),
    (
        "0038_fingerprint_force_heap_scan",
        include_str!("../sql/migrations/0038_fingerprint_force_heap_scan.sql"),
    ),
    (
        "0039_route_overlay",
        include_str!("../sql/migrations/0039_route_overlay.sql"),
    ),
    (
        "0040_route_optimization_candidates",
        include_str!("../sql/migrations/0040_route_optimization_candidates.sql"),
    ),
    (
        "0041_route_shape_samples",
        include_str!("../sql/migrations/0041_route_shape_samples.sql"),
    ),
    (
        "0042_route_optimize_runs",
        include_str!("../sql/migrations/0042_route_optimize_runs.sql"),
    ),
    (
        "0043_cube_refresh_resource_cap",
        include_str!("../sql/migrations/0043_cube_refresh_resource_cap.sql"),
    ),
    (
        "0044_cold_tier_object_store",
        include_str!("../sql/migrations/0044_cold_tier_object_store.sql"),
    ),
    (
        "0045_cold_tier_keep_policy",
        include_str!("../sql/migrations/0045_cold_tier_keep_policy.sql"),
    ),
    (
        "0046_brain_remote_sources",
        include_str!("../sql/migrations/0046_brain_remote_sources.sql"),
    ),
    (
        "0047_brain_sync_orchestration",
        include_str!("../sql/migrations/0047_brain_sync_orchestration.sql"),
    ),
    (
        "0048_brain_kg_enrichment",
        include_str!("../sql/migrations/0048_brain_kg_enrichment.sql"),
    ),
    (
        "0049_brain_source_delete_and_relations",
        include_str!("../sql/migrations/0049_brain_source_delete_and_relations.sql"),
    ),
    (
        "0050_brain_agent_retrieval",
        include_str!("../sql/migrations/0050_brain_agent_retrieval.sql"),
    ),
    (
        "0051_brain_chunk_entities",
        include_str!("../sql/migrations/0051_brain_chunk_entities.sql"),
    ),
    (
        "0052_brain_ner_pass",
        include_str!("../sql/migrations/0052_brain_ner_pass.sql"),
    ),
    (
        "0053_brain_enrich_clean_and_filter",
        include_str!("../sql/migrations/0053_brain_enrich_clean_and_filter.sql"),
    ),
    (
        "0054_brain_related_shared_entities",
        include_str!("../sql/migrations/0054_brain_related_shared_entities.sql"),
    ),
    (
        "0055_brain_ner_full_coverage",
        include_str!("../sql/migrations/0055_brain_ner_full_coverage.sql"),
    ),
    (
        "0056_brain_entity_denoise",
        include_str!("../sql/migrations/0056_brain_entity_denoise.sql"),
    ),
    (
        "0057_brain_related_tfidf",
        include_str!("../sql/migrations/0057_brain_related_tfidf.sql"),
    ),
    (
        "0058_brain_entity_normalization",
        include_str!("../sql/migrations/0058_brain_entity_normalization.sql"),
    ),
    (
        "0059_brain_norm_cache",
        include_str!("../sql/migrations/0059_brain_norm_cache.sql"),
    ),
    (
        "0060_brain_shared_idf_floor",
        include_str!("../sql/migrations/0060_brain_shared_idf_floor.sql"),
    ),
    (
        "0061_brain_norm_preserve",
        include_str!("../sql/migrations/0061_brain_norm_preserve.sql"),
    ),
    (
        "0062_brain_query_sources",
        include_str!("../sql/migrations/0062_brain_query_sources.sql"),
    ),
    (
        "0063_brain_structured_edges",
        include_str!("../sql/migrations/0063_brain_structured_edges.sql"),
    ),
    (
        "0064_brain_enrich_source",
        include_str!("../sql/migrations/0064_brain_enrich_source.sql"),
    ),
    (
        "0065_brain_enrich_pending_fair",
        include_str!("../sql/migrations/0065_brain_enrich_pending_fair.sql"),
    ),
    (
        "0066_vector_sources_tier",
        include_str!("../sql/migrations/0066_vector_sources_tier.sql"),
    ),
    (
        "0067_brain_search_filtered",
        include_str!("../sql/migrations/0067_brain_search_filtered.sql"),
    ),
    (
        "0068_brain_doc_type_facets",
        include_str!("../sql/migrations/0068_brain_doc_type_facets.sql"),
    ),
    (
        "0069_fireflies_mcp_capability",
        include_str!("../sql/migrations/0069_fireflies_mcp_capability.sql"),
    ),
    (
        "0070_agent_loop",
        include_str!("../sql/migrations/0070_agent_loop.sql"),
    ),
    (
        "0071_accel_dirty_ops_guard",
        include_str!("../sql/migrations/0071_accel_dirty_ops_guard.sql"),
    ),
    (
        "0072_accel_pk_tombstone_overlay",
        include_str!("../sql/migrations/0072_accel_pk_tombstone_overlay.sql"),
    ),
    (
        "0073_accel_ctid_identity_overlay",
        include_str!("../sql/migrations/0073_accel_ctid_identity_overlay.sql"),
    ),
    (
        "0074_accel_ctid_relfilenode_guard",
        include_str!("../sql/migrations/0074_accel_ctid_relfilenode_guard.sql"),
    ),
    (
        "0075_accel_auto_consolidation",
        include_str!("../sql/migrations/0075_accel_auto_consolidation.sql"),
    ),
    (
        "0076_accel_staged_fold_swap",
        include_str!("../sql/migrations/0076_accel_staged_fold_swap.sql"),
    ),
    (
        "0077_accel_orphan_reap_maintenance",
        include_str!("../sql/migrations/0077_accel_orphan_reap_maintenance.sql"),
    ),
    (
        "0078_accel_lagged_fold_catchup",
        include_str!("../sql/migrations/0078_accel_lagged_fold_catchup.sql"),
    ),
    (
        "0079_accel_sharded_dirty_markers",
        include_str!("../sql/migrations/0079_accel_sharded_dirty_markers.sql"),
    ),
    (
        "0080_accel_partition_dirty_triggers",
        include_str!("../sql/migrations/0080_accel_partition_dirty_triggers.sql"),
    ),
    (
        "0081_accel_partition_attach_reinstall",
        include_str!("../sql/migrations/0081_accel_partition_attach_reinstall.sql"),
    ),
    (
        "0082_accel_identity_remap_index",
        include_str!("../sql/migrations/0082_accel_identity_remap_index.sql"),
    ),
    (
        "0083_cube_refresh_autopilot",
        include_str!("../sql/migrations/0083_cube_refresh_autopilot.sql"),
    ),
    (
        "0084_cube_refresh_selective_sweeps",
        include_str!("../sql/migrations/0084_cube_refresh_selective_sweeps.sql"),
    ),
    (
        "0085_operator_update_flush_cache",
        include_str!("../sql/migrations/0085_operator_update_flush_cache.sql"),
    ),
    (
        "0086_accel_fold_snapshot_floor_guard",
        include_str!("../sql/migrations/0086_accel_fold_snapshot_floor_guard.sql"),
    ),
    (
        "0087_cube_variant_status_counts",
        include_str!("../sql/migrations/0087_cube_variant_status_counts.sql"),
    ),
    (
        "0088_unified_maintenance_surface",
        include_str!("../sql/migrations/0088_unified_maintenance_surface.sql"),
    ),
    (
        "0089_snapshot_visible_tombstones",
        include_str!("../sql/migrations/0089_snapshot_visible_tombstones.sql"),
    ),
    (
        "0090_scalar_metric_observations",
        include_str!("../sql/migrations/0090_scalar_metric_observations.sql"),
    ),
    (
        "0091_metric_dependency_freshness",
        include_str!("../sql/migrations/0091_metric_dependency_freshness.sql"),
    ),
    (
        "0092_metric_series",
        include_str!("../sql/migrations/0092_metric_series.sql"),
    ),
    (
        "0093_visual_rowset_operators",
        include_str!("../sql/migrations/0093_visual_rowset_operators.sql"),
    ),
    (
        "0094_accelerator_runtime_status",
        include_str!("../sql/migrations/0094_accelerator_runtime_status.sql"),
    ),
    (
        "0095_registry_first_acceleration",
        include_str!("../sql/migrations/0095_registry_first_acceleration.sql"),
    ),
    (
        "0096_filter_control_operator",
        include_str!("../sql/migrations/0096_filter_control_operator.sql"),
    ),
    (
        "0097_layout_grid_operator",
        include_str!("../sql/migrations/0097_layout_grid_operator.sql"),
    ),
    (
        "0098_tile_name_operator",
        include_str!("../sql/migrations/0098_tile_name_operator.sql"),
    ),
    (
        "0099_bind_filter_operator",
        include_str!("../sql/migrations/0099_bind_filter_operator.sql"),
    ),
    (
        "0100_layout_grid_json_args",
        include_str!("../sql/migrations/0100_layout_grid_json_args.sql"),
    ),
    (
        "0101_line_scatter_visual_operators",
        include_str!("../sql/migrations/0101_line_scatter_visual_operators.sql"),
    ),
    (
        "0102_filter_control_defaults",
        include_str!("../sql/migrations/0102_filter_control_defaults.sql"),
    ),
    (
        "0103_action_button_operator",
        include_str!("../sql/migrations/0103_action_button_operator.sql"),
    ),
    (
        "0104_hindsight_memory_service",
        include_str!("../sql/migrations/0104_hindsight_memory_service.sql"),
    ),
    (
        "0105_hindsight_catalog_visibility",
        include_str!("../sql/migrations/0105_hindsight_catalog_visibility.sql"),
    ),
    (
        "0106_hindsight_sql_wrappers",
        include_str!("../sql/migrations/0106_hindsight_sql_wrappers.sql"),
    ),
    (
        "0107_viz_blocks",
        include_str!("../sql/migrations/0107_viz_blocks.sql"),
    ),
    (
        "0108_operator_model_setter",
        include_str!("../sql/migrations/0108_operator_model_setter.sql"),
    ),
    (
        "0109_workload_layout_advisor",
        include_str!("../sql/migrations/0109_workload_layout_advisor.sql"),
    ),
    (
        "0110_workload_layout_build_status",
        include_str!("../sql/migrations/0110_workload_layout_build_status.sql"),
    ),
    (
        "0111_n8n_operator_node",
        include_str!("../sql/migrations/0111_n8n_operator_node.sql"),
    ),
    (
        "0112_drop_table_orphan_files",
        include_str!("../sql/migrations/0112_drop_table_orphan_files.sql"),
    ),
    (
        "0113_datafusion_vortex_profile_metric",
        include_str!("../sql/migrations/0113_datafusion_vortex_profile_metric.sql"),
    ),
    (
        "0114_route_shape_summary_datafusion_vortex_outputs",
        include_str!("../sql/migrations/0114_route_shape_summary_datafusion_vortex_outputs.sql"),
    ),
    (
        "0115_system_learning_brain_provider",
        include_str!("../sql/migrations/0115_system_learning_brain_provider.sql"),
    ),
    (
        "0116_gpu_gqe_route_candidate",
        include_str!("../sql/migrations/0116_gpu_gqe_route_candidate.sql"),
    ),
    (
        "0117_clickbench_gpu_stock_route_overlay",
        include_str!("../sql/migrations/0117_clickbench_gpu_stock_route_overlay.sql"),
    ),
    (
        "0118_rebuild_acceleration_dataloss_guard",
        include_str!("../sql/migrations/0118_rebuild_acceleration_dataloss_guard.sql"),
    ),
    (
        "0119_clickbench_1m_route_overlay_refresh",
        include_str!("../sql/migrations/0119_clickbench_1m_route_overlay_refresh.sql"),
    ),
    (
        "0120_html_block_turn_operator",
        include_str!("../sql/migrations/0120_html_block_turn_operator.sql"),
    ),
    (
        "0121_reap_generations_defer_unlink",
        include_str!("../sql/migrations/0121_reap_generations_defer_unlink.sql"),
    ),
    (
        "0122_shadow_heap_triggers_enable_always",
        include_str!("../sql/migrations/0122_shadow_heap_triggers_enable_always.sql"),
    ),
    (
        "0123_refresh_watermark_visibility_guard",
        include_str!("../sql/migrations/0123_refresh_watermark_visibility_guard.sql"),
    ),
    (
        "0124_gqe_warm_prior_routing",
        include_str!("../sql/migrations/0124_gqe_warm_prior_routing.sql"),
    ),
    (
        "0125_route_model",
        include_str!("../sql/migrations/0125_route_model.sql"),
    ),
    (
        "0126_train_route_model_binding",
        include_str!("../sql/migrations/0126_train_route_model_binding.sql"),
    ),
    (
        "0127_route_self_train_binding",
        include_str!("../sql/migrations/0127_route_self_train_binding.sql"),
    ),
    (
        "0128_route_shape_samples_search_path",
        include_str!("../sql/migrations/0128_route_shape_samples_search_path.sql"),
    ),
    (
        "0129_route_shape_samples_test_memory",
        include_str!("../sql/migrations/0129_route_shape_samples_test_memory.sql"),
    ),
    (
        "0130_route_model_factory_seed",
        include_str!("../sql/migrations/0130_route_model_factory_seed.sql"),
    ),
    (
        "0131_refresh_same_txn_pending_visibility",
        include_str!("../sql/migrations/0131_refresh_same_txn_pending_visibility.sql"),
    ),
    (
        "0132_gqe_warm_public_tables",
        include_str!("../sql/migrations/0132_gqe_warm_public_tables.sql"),
    ),
    (
        "0133_html_block_turn_data_contract",
        include_str!("../sql/migrations/0133_html_block_turn_data_contract.sql"),
    ),
    (
        "0134_read_fleet_prework",
        include_str!("../sql/migrations/0134_read_fleet_prework.sql"),
    ),
    (
        "0135_publish_lifecycle",
        include_str!("../sql/migrations/0135_publish_lifecycle.sql"),
    ),
    (
        "0136_fleet_endpoints",
        include_str!("../sql/migrations/0136_fleet_endpoints.sql"),
    ),
    (
        "0137_route_executions_node",
        include_str!("../sql/migrations/0137_route_executions_node.sql"),
    ),
    (
        "0138_metadata_maintenance",
        include_str!("../sql/migrations/0138_metadata_maintenance.sql"),
    ),
    (
        "0139_hare_capsule",
        include_str!("../sql/migrations/0139_hare_capsule.sql"),
    ),
    (
        "0140_hare_observability",
        include_str!("../sql/migrations/0140_hare_observability.sql"),
    ),
    (
        "0141_executed_engine",
        include_str!("../sql/migrations/0141_executed_engine.sql"),
    ),
    (
        "0142_sidecar_mode_check",
        include_str!("../sql/migrations/0142_sidecar_mode_check.sql"),
    ),
    (
        "0143_secrets",
        include_str!("../sql/migrations/0143_secrets.sql"),
    ),
    (
        "0144_operator_test_runs",
        include_str!("../sql/migrations/0144_operator_test_runs.sql"),
    ),
    (
        "0145_test_cache_bypass",
        include_str!("../sql/migrations/0145_test_cache_bypass.sql"),
    ),
    (
        "0146_desktop_assistant_turn_operator",
        include_str!("../sql/migrations/0146_desktop_assistant_turn_operator.sql"),
    ),
    (
        "0147_capability_kg",
        include_str!("../sql/migrations/0147_capability_kg.sql"),
    ),
    (
        "0148_engine_rows",
        include_str!("../sql/migrations/0148_engine_rows.sql"),
    ),
    (
        "0149_backend_health_llm_usage",
        include_str!("../sql/migrations/0149_backend_health_llm_usage.sql"),
    ),
    (
        "0150_assistant_output_guard",
        include_str!("../sql/migrations/0150_assistant_output_guard.sql"),
    ),
    (
        "0151_assistant_execution_feedback",
        include_str!("../sql/migrations/0151_assistant_execution_feedback.sql"),
    ),
    (
        "0152_assistant_provider_failures",
        include_str!("../sql/migrations/0152_assistant_provider_failures.sql"),
    ),
    (
        "0153_assistant_vision",
        include_str!("../sql/migrations/0153_assistant_vision.sql"),
    ),
    (
        "0154_time_travel_retention",
        include_str!("../sql/migrations/0154_time_travel_retention.sql"),
    ),
    (
        "0155_disambiguate_maintain",
        include_str!("../sql/migrations/0155_disambiguate_maintain.sql"),
    ),
    (
        "0156_warren_heartbeat_churn",
        include_str!("../sql/migrations/0156_warren_heartbeat_churn.sql"),
    ),
    (
        "0157_plates",
        include_str!("../sql/migrations/0157_plates.sql"),
    ),
    (
        "0158_kit_contracts",
        include_str!("../sql/migrations/0158_kit_contracts.sql"),
    ),
    (
        "0159_system_plates",
        include_str!("../sql/migrations/0159_system_plates.sql"),
    ),
    (
        "0160_assistant_plates",
        include_str!("../sql/migrations/0160_assistant_plates.sql"),
    ),
    (
        "0161_assistant_plate_kits",
        include_str!("../sql/migrations/0161_assistant_plate_kits.sql"),
    ),
    (
        "0162_kit_packaging",
        include_str!("../sql/migrations/0162_kit_packaging.sql"),
    ),
    (
        "0163_system_kit_grouping",
        include_str!("../sql/migrations/0163_system_kit_grouping.sql"),
    ),
    (
        "0164_kit_rules",
        include_str!("../sql/migrations/0164_kit_rules.sql"),
    ),
    (
        "0165_operator_kit_scope",
        include_str!("../sql/migrations/0165_operator_kit_scope.sql"),
    ),
    (
        "0166_assistant_kit_logic",
        include_str!("../sql/migrations/0166_assistant_kit_logic.sql"),
    ),
    (
        "0167_rule_observability",
        include_str!("../sql/migrations/0167_rule_observability.sql"),
    ),
    (
        "0168_kit_lifecycle",
        include_str!("../sql/migrations/0168_kit_lifecycle.sql"),
    ),
    (
        "0169_kit_roles",
        include_str!("../sql/migrations/0169_kit_roles.sql"),
    ),
    (
        "0170_assistant_plate_optin",
        include_str!("../sql/migrations/0170_assistant_plate_optin.sql"),
    ),
    (
        "0171_kit_fitting",
        include_str!("../sql/migrations/0171_kit_fitting.sql"),
    ),
    (
        "0172_fitting_llm_draft",
        include_str!("../sql/migrations/0172_fitting_llm_draft.sql"),
    ),
    (
        "0173_fitting_value_contracts",
        include_str!("../sql/migrations/0173_fitting_value_contracts.sql"),
    ),
    (
        "0174_assistant_register_kit",
        include_str!("../sql/migrations/0174_assistant_register_kit.sql"),
    ),
    (
        "0175_kit_composition",
        include_str!("../sql/migrations/0175_kit_composition.sql"),
    ),
    (
        "0176_assistant_plate_patterns",
        include_str!("../sql/migrations/0176_assistant_plate_patterns.sql"),
    ),
    (
        "0177_assistant_layout_palette",
        include_str!("../sql/migrations/0177_assistant_layout_palette.sql"),
    ),
    (
        "0178_assistant_board_island",
        include_str!("../sql/migrations/0178_assistant_board_island.sql"),
    ),
    (
        "0179_assistant_edit_loop",
        include_str!("../sql/migrations/0179_assistant_edit_loop.sql"),
    ),
    (
        "0180_assistant_utility_palette",
        include_str!("../sql/migrations/0180_assistant_utility_palette.sql"),
    ),
    (
        "0181_assistant_chart_autosize",
        include_str!("../sql/migrations/0181_assistant_chart_autosize.sql"),
    ),
    (
        "0182_plate_revisions",
        include_str!("../sql/migrations/0182_plate_revisions.sql"),
    ),
    (
        "0183_assistant_chart_spec",
        include_str!("../sql/migrations/0183_assistant_chart_spec.sql"),
    ),
    (
        "0184_assistant_config_comments",
        include_str!("../sql/migrations/0184_assistant_config_comments.sql"),
    ),
    (
        "0185_assistant_editable_grid",
        include_str!("../sql/migrations/0185_assistant_editable_grid.sql"),
    ),
    (
        "0186_assistant_patch_plate",
        include_str!("../sql/migrations/0186_assistant_patch_plate.sql"),
    ),
    (
        "0187_plate_layouts",
        include_str!("../sql/migrations/0187_plate_layouts.sql"),
    ),
    (
        "0188_assistant_layouts",
        include_str!("../sql/migrations/0188_assistant_layouts.sql"),
    ),
    (
        "0189_assistant_block_sizing",
        include_str!("../sql/migrations/0189_assistant_block_sizing.sql"),
    ),
    (
        "0190_desktop_panels",
        include_str!("../sql/migrations/0190_desktop_panels.sql"),
    ),
    (
        "0191_assistant_open_panel",
        include_str!("../sql/migrations/0191_assistant_open_panel.sql"),
    ),
    (
        "0192_assistant_inline_styles",
        include_str!("../sql/migrations/0192_assistant_inline_styles.sql"),
    ),
    (
        "0193_provider_test",
        include_str!("../sql/migrations/0193_provider_test.sql"),
    ),
    (
        "0194_credential_state",
        include_str!("../sql/migrations/0194_credential_state.sql"),
    ),
    (
        "0195_managed_provider_models",
        include_str!("../sql/migrations/0195_managed_provider_models.sql"),
    ),
    (
        "0196_gdrive_connector_backend",
        include_str!("../sql/migrations/0196_gdrive_connector_backend.sql"),
    ),
    (
        "0197_brain_ingest_folder",
        include_str!("../sql/migrations/0197_brain_ingest_folder.sql"),
    ),
    (
        "0198_mcp_capability_freshness",
        include_str!("../sql/migrations/0198_mcp_capability_freshness.sql"),
    ),
    (
        "0199_capability_crawl_on_catalog_crawl",
        include_str!("../sql/migrations/0199_capability_crawl_on_catalog_crawl.sql"),
    ),
    (
        "0200_hub_front_door",
        include_str!("../sql/migrations/0200_hub_front_door.sql"),
    ),
    (
        "0201_hub_open_ergonomics",
        include_str!("../sql/migrations/0201_hub_open_ergonomics.sql"),
    ),
    (
        "0202_hub_peek_data",
        include_str!("../sql/migrations/0202_hub_peek_data.sql"),
    ),
    (
        "0203_burrow_enroll",
        include_str!("../sql/migrations/0203_burrow_enroll.sql"),
    ),
    (
        "0204_headless_plates_kit_pulse",
        include_str!("../sql/migrations/0204_headless_plates_kit_pulse.sql"),
    ),
    (
        "0205_kit_public_surface",
        include_str!("../sql/migrations/0205_kit_public_surface.sql"),
    ),
    (
        "0206_kit_brief",
        include_str!("../sql/migrations/0206_kit_brief.sql"),
    ),
    (
        "0207_data_crawl_run",
        include_str!("../sql/migrations/0207_data_crawl_run.sql"),
    ),
];

const SCHEMA_MIGRATIONS_DDL: &str = "\
CREATE TABLE IF NOT EXISTS rvbbit.schema_migrations (
    name        text PRIMARY KEY,
    applied_at  timestamptz NOT NULL DEFAULT now()
)";

fn sql_quote(s: &str) -> String {
    s.replace('\'', "''")
}

/// Apply every embedded migration not yet recorded, in order, recording each in
/// `rvbbit.schema_migrations`. Returns a one-line summary.
///
/// Runs in the caller's transaction: the pending set is applied atomically — if
/// any migration fails the whole call aborts and nothing is recorded, so you fix
/// it and re-run (migrations are idempotent). Safe to call on every deploy;
/// schema migrations are a no-op once applied, but the embedded curated
/// capability catalog is refreshed each time so catalog-only fixes ship with
/// normal extension upgrades.
#[pg_extern]
fn migrate() -> String {
    Spi::run(SCHEMA_MIGRATIONS_DDL).expect("rvbbit.migrate: create schema_migrations");
    // Migration SQL creates/replaces catalog views and may run while extension
    // catalog state is still being normalized. Keep the planner/rewriter hooks
    // out of this transaction; they are user-query optimizers, not DDL helpers.
    Spi::run("SET LOCAL rvbbit.force_heap_scan = on")
        .expect("rvbbit.migrate: disable planner/rewriter hooks");

    let mut applied: Vec<&str> = Vec::new();
    for (name, sql) in MIGRATIONS {
        let done = Spi::get_one::<bool>(&format!(
            "SELECT EXISTS(SELECT 1 FROM rvbbit.schema_migrations WHERE name = '{}')",
            sql_quote(name)
        ))
        .unwrap_or(Some(false))
        .unwrap_or(false);
        if done {
            continue;
        }
        if let Err(e) = Spi::run(sql) {
            pgrx::error!("rvbbit.migrate: migration '{}' failed: {:?}", name, e);
        }
        Spi::run(&format!(
            "INSERT INTO rvbbit.schema_migrations (name) VALUES ('{}')",
            sql_quote(name)
        ))
        .unwrap_or_else(|e| pgrx::error!("rvbbit.migrate: recording '{}' failed: {:?}", name, e));
        applied.push(name);
    }

    Spi::run("SELECT rvbbit.seed_capability_catalog()").unwrap_or_else(|e| {
        pgrx::error!("rvbbit.migrate: seed capability catalog failed: {:?}", e)
    });

    if applied.is_empty() {
        format!(
            "rvbbit.migrate: up to date ({} migration(s) known)",
            MIGRATIONS.len()
        )
    } else {
        format!(
            "rvbbit.migrate: applied {} of {} — {}",
            applied.len(),
            MIGRATIONS.len(),
            applied.join(", ")
        )
    }
}

/// List every embedded migration and whether it has been applied. Read-only
/// companion to migrate() for inspection.
#[pg_extern]
fn migrations_status() -> TableIterator<'static, (name!(name, String), name!(applied, bool))> {
    // Tolerate a never-migrated database (no schema_migrations yet).
    let _ = Spi::run(SCHEMA_MIGRATIONS_DDL);
    let rows: Vec<(String, bool)> = MIGRATIONS
        .iter()
        .map(|(name, _)| {
            let done = Spi::get_one::<bool>(&format!(
                "SELECT EXISTS(SELECT 1 FROM rvbbit.schema_migrations WHERE name = '{}')",
                sql_quote(name)
            ))
            .unwrap_or(Some(false))
            .unwrap_or(false);
            (name.to_string(), done)
        })
        .collect();
    TableIterator::new(rows.into_iter())
}
