-- 0162: kit packaging — kits become shippable artifacts (KIT_PLATES_PLAN §16).
--
-- A kit travels as pure SQL, Clover-style local install: export_kit() renders
-- every row the kit owns (registry metadata + setup DDL + plates + module
-- assignments + contracts) as an ordered, idempotent statement script;
-- publish_kit() wraps that script in a kind='kit' capability_catalog entry so
-- kits ride the existing catalog channels (capability_search, catalog.json
-- import, downloadable <kit>-install.sql). Reserved manifest sections for
-- operators / rules / metric_defs / cube_defs keep the format stable when the
-- switchboard logic tier lands.

CREATE TABLE IF NOT EXISTS rvbbit.kits (
    kit         text PRIMARY KEY,
    version     text NOT NULL DEFAULT '0.1.0',
    title       text,
    description text,
    -- Idempotent DDL prologue: schemas, kit-owned tables/views, roles/grants.
    -- Runs FIRST on install; the author owns its idempotency (IF NOT EXISTS).
    setup_sql   text,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE OR REPLACE FUNCTION rvbbit.upsert_kit(
    p_kit text,
    p_title text,
    p_description text DEFAULT NULL,
    p_setup_sql text DEFAULT NULL,
    p_version text DEFAULT '0.1.0'
) RETURNS void
LANGUAGE sql
AS $uk$
    INSERT INTO rvbbit.kits (kit, version, title, description, setup_sql)
    VALUES (p_kit, p_version, p_title, p_description, p_setup_sql)
    ON CONFLICT (kit) DO UPDATE SET
        version = EXCLUDED.version,
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        setup_sql = EXCLUDED.setup_sql,
        updated_at = clock_timestamp();
$uk$;

-- Dollar-quote a body with a tag guaranteed not to collide with the content.
CREATE OR REPLACE FUNCTION rvbbit._kit_dq(p_body text, p_base text)
RETURNS text
LANGUAGE plpgsql IMMUTABLE
AS $dq$
DECLARE
    tag text;
    i int := 0;
BEGIN
    LOOP
        tag := '$' || p_base || CASE WHEN i = 0 THEN '' ELSE i::text END || '$';
        EXIT WHEN position(tag IN coalesce(p_body, '')) = 0;
        i := i + 1;
    END LOOP;
    RETURN tag || coalesce(p_body, '') || tag;
END
$dq$;

-- Render a kit as a self-contained, idempotent install script. The installer
-- (psql, catalog import, an agent) should run it inside ONE transaction and
-- validate with ROLLBACK first — statements are plain SQL, no psql-isms.
CREATE OR REPLACE FUNCTION rvbbit.export_kit(p_kit text)
RETURNS text
LANGUAGE plpgsql
AS $ek$
DECLARE
    k rvbbit.kits%ROWTYPE;
    v_out text;
    v_plates text;
    v_modules text;
    v_contracts text;
BEGIN
    SELECT * INTO k FROM rvbbit.kits WHERE kit = p_kit;
    IF NOT FOUND THEN
        -- A kit can exist purely as tagged plates; synthesize minimal metadata.
        IF NOT EXISTS (SELECT 1 FROM rvbbit.plates WHERE kit = p_kit) THEN
            RAISE EXCEPTION 'export_kit: no kit named %', p_kit;
        END IF;
        k.kit := p_kit;
        k.version := '0.0.0';
        k.title := p_kit;
        k.description := NULL;
        k.setup_sql := NULL;
    END IF;

    v_out := format(E'-- rvbbit kit: %s v%s\n-- generated by rvbbit.export_kit() · api rvbbit.kit/v1\n-- Install: run this whole file in ONE transaction (validate with ROLLBACK first).\n\n',
                    k.kit, k.version);

    v_out := v_out || format(E'SELECT rvbbit.upsert_kit(%L, %L, %s, %s, %L);\n\n',
        k.kit, k.title,
        CASE WHEN k.description IS NULL THEN 'NULL' ELSE quote_literal(k.description) END,
        CASE WHEN k.setup_sql IS NULL THEN 'NULL' ELSE rvbbit._kit_dq(k.setup_sql, 'ksetup') END,
        k.version);

    IF k.setup_sql IS NOT NULL THEN
        v_out := v_out || E'-- ── setup (kit-owned schemas/tables/views/roles) ──\n'
              || k.setup_sql || E'\n\n';
    END IF;

    SELECT string_agg(
        format(E'SELECT rvbbit.upsert_plate(%L, %L, %s, %s::jsonb, %s::jsonb, %s::jsonb, %L, %s, %s);',
            p.plate_id, p.title,
            rvbbit._kit_dq(p.template, 'ktpl'),
            rvbbit._kit_dq(p.queries::text, 'kq'),
            rvbbit._kit_dq(p.actions::text, 'ka'),
            rvbbit._kit_dq(p.params::text, 'kp'),
            p.kit,
            CASE WHEN p.description IS NULL THEN 'NULL' ELSE quote_literal(p.description) END,
            p.template_version),
        E'\n' ORDER BY p.plate_id)
    INTO v_plates
    FROM rvbbit.plates p WHERE p.kit = p_kit;

    SELECT string_agg(
        format('UPDATE rvbbit.plates SET module = %L WHERE plate_id = %L;', p.module, p.plate_id),
        E'\n' ORDER BY p.plate_id)
    INTO v_modules
    FROM rvbbit.plates p WHERE p.kit = p_kit AND p.module IS NOT NULL;

    SELECT string_agg(
        format('SELECT rvbbit.upsert_kit_contract(%L, %L, %L, %s, %s);',
            c.kit, c.module, c.contract_id,
            rvbbit._kit_dq(c.violations_sql, 'kv'),
            CASE WHEN c.description IS NULL THEN 'NULL' ELSE quote_literal(c.description) END),
        E'\n' ORDER BY c.module, c.contract_id)
    INTO v_contracts
    FROM rvbbit.kit_contracts c WHERE c.kit = p_kit;

    v_out := v_out
        || E'-- ── plates ──\n' || coalesce(v_plates, '-- (none)') || E'\n\n'
        || E'-- ── module assignments ──\n' || coalesce(v_modules, '-- (none)') || E'\n\n'
        || E'-- ── contracts (empty result = green) ──\n' || coalesce(v_contracts, '-- (none)') || E'\n\n'
        || E'-- ── operators (reserved: kit-scoped operators land here) ──\n-- (none)\n\n'
        || E'-- ── rules (reserved: rvbbit.kit_rules decision tables land here) ──\n-- (none)\n\n'
        || E'-- ── metric_defs (reserved: definitions bound to kit canonical views) ──\n-- (none)\n\n'
        || E'-- ── cube_defs (reserved) ──\n-- (none)\n';

    RETURN v_out;
END
$ek$;

-- Publish a kit into the local capability catalog (kind='kit'): the install
-- script rides manifest.install_sql, so kits flow through the same channels
-- as every other capability — capability_search, catalog export/import.
CREATE OR REPLACE FUNCTION rvbbit.publish_kit(p_kit text)
RETURNS text
LANGUAGE plpgsql
AS $pk$
DECLARE
    k rvbbit.kits%ROWTYPE;
    v_sql text;
    v_id text;
    v_manifest jsonb;
BEGIN
    SELECT * INTO k FROM rvbbit.kits WHERE kit = p_kit;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'publish_kit: register the kit first with rvbbit.upsert_kit()';
    END IF;
    v_sql := rvbbit.export_kit(p_kit);
    v_id := 'kit/' || p_kit;
    v_manifest := jsonb_build_object(
        'api_version', 'rvbbit.capability/v1',
        'kind', 'kit',
        'name', p_kit,
        'title', coalesce(k.title, p_kit),
        'description', coalesce(k.description, ''),
        'version', k.version,
        'tags', jsonb_build_array('kit', 'plates'),
        'install_sql', v_sql
    );
    INSERT INTO rvbbit.capability_catalog
        (id, name, title, description, tags, kind, operators, manifest, catalog_entry, catalog_source, active)
    VALUES
        (v_id, p_kit, coalesce(k.title, p_kit), coalesce(k.description, ''),
         ARRAY['kit', 'plates'], 'kit', ARRAY[]::text[], v_manifest, v_manifest, 'local', true)
    ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        manifest = EXCLUDED.manifest,
        catalog_entry = EXCLUDED.catalog_entry,
        active = true,
        updated_at = clock_timestamp();
    RETURN v_id;
END
$pk$;
