-- 0165: kit-scoped operators (KIT_PLATES_PLAN §6, tier 3) + export_kit v2.
--
-- Operators gain kit + visibility. visibility='kit' means PRIVATE to the kit:
-- excluded from capability_crawl indexing (anchored patch of the LIVE crawl
-- definition — the prompt-patch pattern applied to a function, fails loudly on
-- drift), its search doc removed on hide, and lens pickers filter it. The
-- operator still RUNS everywhere — plate actions and kit SQL call it by name;
-- scoping is discovery hygiene, not an execution wall (GRANTs stay the wall).
-- export_kit v2 ships rules + kit operators in the reserved sections.

ALTER TABLE rvbbit.operators ADD COLUMN IF NOT EXISTS kit text;
ALTER TABLE rvbbit.operators ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'public';
DO $ck$
BEGIN
    ALTER TABLE rvbbit.operators
        ADD CONSTRAINT operators_visibility_check CHECK (visibility IN ('public', 'kit'));
EXCEPTION WHEN duplicate_object THEN NULL;
END
$ck$;

CREATE OR REPLACE FUNCTION rvbbit.set_operator_kit(
    p_operator text,
    p_kit text,
    p_visibility text DEFAULT 'kit'
) RETURNS void
LANGUAGE plpgsql
AS $sok$
BEGIN
    UPDATE rvbbit.operators
    SET kit = p_kit, visibility = p_visibility, updated_at = clock_timestamp()
    WHERE name = p_operator;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'set_operator_kit: no operator named %', p_operator;
    END IF;
    -- Hiding removes the discovery doc immediately; the patched crawl keeps
    -- it out on every future re-crawl.
    IF p_visibility = 'kit' THEN
        DELETE FROM rvbbit.catalog_docs
        WHERE kind = 'cap_operator' AND rel_name = p_operator;
    END IF;
END
$sok$;

-- Patch the LIVE capability_crawl so kit-private operators stay out of the
-- discovery index. Two anchored edits; skip if already patched; fail loudly
-- if the anchors drifted.
DO $patch$
DECLARE
    v_def text;
    v_a text := 'FOR rec IN SELECT o.* FROM rvbbit.operators o LOOP';
    v_a2 text := 'FOR rec IN SELECT o.* FROM rvbbit.operators o WHERE coalesce(o.visibility, ''public'') <> ''kit'' LOOP';
    v_b text := E'FROM rvbbit.operators o\n                ) all_docs';
    v_b2 text := E'FROM rvbbit.operators o WHERE coalesce(o.visibility, ''public'') <> ''kit''\n                ) all_docs';
BEGIN
    SELECT pg_get_functiondef(p.oid) INTO v_def
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'rvbbit' AND p.proname = 'capability_crawl';
    IF v_def IS NULL THEN
        RAISE NOTICE '0165: capability_crawl not installed; skipping crawl patch';
        RETURN;
    END IF;
    IF position('coalesce(o.visibility' IN v_def) > 0 THEN
        RAISE NOTICE '0165: capability_crawl already excludes kit operators; skipping';
        RETURN;
    END IF;
    IF (length(v_def) - length(replace(v_def, v_a, ''))) / length(v_a) <> 1 THEN
        RAISE EXCEPTION '0165: crawl loop anchor not found exactly once — re-author this patch';
    END IF;
    IF (length(v_def) - length(replace(v_def, v_b, ''))) / length(v_b) <> 1 THEN
        RAISE EXCEPTION '0165: crawl union anchor not found exactly once — re-author this patch';
    END IF;
    v_def := replace(v_def, v_a, v_a2);
    v_def := replace(v_def, v_b, v_b2);
    EXECUTE v_def;
    RAISE NOTICE '0165: capability_crawl patched — kit-private operators excluded from discovery';
END
$patch$;

-- One-time sweep for docs of operators already private before this migration.
DELETE FROM rvbbit.catalog_docs
WHERE kind = 'cap_operator'
  AND rel_name IN (SELECT name FROM rvbbit.operators WHERE visibility = 'kit');

-- export_kit v2: rules + kit-scoped operators travel. Operators export as
-- DELETE + jsonb_populate_record INSERT — tolerant of column drift in both
-- directions (missing keys → defaults, unknown keys → ignored).
CREATE OR REPLACE FUNCTION rvbbit.export_kit(p_kit text)
RETURNS text
LANGUAGE plpgsql
AS $ek$
DECLARE
    k rvbbit.kits%ROWTYPE;
    v_out text;
    v_plates text;
    v_modules text;
    v_contracts text;
    v_rules text;
    v_ops text;
BEGIN
    SELECT * INTO k FROM rvbbit.kits WHERE kit = p_kit;
    IF NOT FOUND THEN
        IF NOT EXISTS (SELECT 1 FROM rvbbit.plates WHERE kit = p_kit) THEN
            RAISE EXCEPTION 'export_kit: no kit named %', p_kit;
        END IF;
        k.kit := p_kit;
        k.version := '0.0.0';
        k.title := p_kit;
        k.description := NULL;
        k.setup_sql := NULL;
    END IF;

    v_out := format(E'-- rvbbit kit: %s v%s\n-- generated by rvbbit.export_kit() · api rvbbit.kit/v1\n-- Install: run this whole file in ONE transaction (validate with ROLLBACK first).\n\n',
                    k.kit, k.version);

    v_out := v_out || format(E'SELECT rvbbit.upsert_kit(%L, %L, %s, %s, %L);\n\n',
        k.kit, k.title,
        CASE WHEN k.description IS NULL THEN 'NULL' ELSE quote_literal(k.description) END,
        CASE WHEN k.setup_sql IS NULL THEN 'NULL' ELSE rvbbit._kit_dq(k.setup_sql, 'ksetup') END,
        k.version);

    IF k.setup_sql IS NOT NULL THEN
        v_out := v_out || E'-- ── setup (kit-owned schemas/tables/views/roles) ──\n'
              || k.setup_sql || E'\n\n';
    END IF;

    SELECT string_agg(
        format(E'SELECT rvbbit.upsert_plate(%L, %L, %s, %s::jsonb, %s::jsonb, %s::jsonb, %L, %s, %s);',
            p.plate_id, p.title,
            rvbbit._kit_dq(p.template, 'ktpl'),
            rvbbit._kit_dq(p.queries::text, 'kq'),
            rvbbit._kit_dq(p.actions::text, 'ka'),
            rvbbit._kit_dq(p.params::text, 'kp'),
            p.kit,
            CASE WHEN p.description IS NULL THEN 'NULL' ELSE quote_literal(p.description) END,
            p.template_version),
        E'\n' ORDER BY p.plate_id)
    INTO v_plates
    FROM rvbbit.plates p WHERE p.kit = p_kit;

    SELECT string_agg(
        format('UPDATE rvbbit.plates SET module = %L WHERE plate_id = %L;', p.module, p.plate_id),
        E'\n' ORDER BY p.plate_id)
    INTO v_modules
    FROM rvbbit.plates p WHERE p.kit = p_kit AND p.module IS NOT NULL;

    SELECT string_agg(
        format('SELECT rvbbit.upsert_kit_contract(%L, %L, %L, %s, %s);',
            c.kit, c.module, c.contract_id,
            rvbbit._kit_dq(c.violations_sql, 'kv'),
            CASE WHEN c.description IS NULL THEN 'NULL' ELSE quote_literal(c.description) END),
        E'\n' ORDER BY c.module, c.contract_id)
    INTO v_contracts
    FROM rvbbit.kit_contracts c WHERE c.kit = p_kit;

    SELECT string_agg(
        format('SELECT rvbbit.upsert_kit_rule(%L, %L, %L, %s, %s::jsonb, %s, %s);',
            r.kit, r.rule_set, r.rule_id,
            rvbbit._kit_dq(r.when_sql, 'kw'),
            rvbbit._kit_dq(r.verdict::text, 'kvj'),
            r.priority,
            CASE WHEN r.description IS NULL THEN 'NULL' ELSE quote_literal(r.description) END),
        E'\n' ORDER BY r.rule_set, r.priority, r.rule_id)
    INTO v_rules
    FROM rvbbit.kit_rules r WHERE r.kit = p_kit AND r.active;

    SELECT string_agg(
        format(E'DELETE FROM rvbbit.operators WHERE name = %L;\nINSERT INTO rvbbit.operators SELECT * FROM jsonb_populate_record(NULL::rvbbit.operators, %s::jsonb);',
            o.name,
            rvbbit._kit_dq(to_jsonb(o)::text, 'kop')),
        E'\n' ORDER BY o.name)
    INTO v_ops
    FROM rvbbit.operators o WHERE o.kit = p_kit;

    v_out := v_out
        || E'-- ── plates ──\n' || coalesce(v_plates, '-- (none)') || E'\n\n'
        || E'-- ── module assignments ──\n' || coalesce(v_modules, '-- (none)') || E'\n\n'
        || E'-- ── contracts (empty result = green) ──\n' || coalesce(v_contracts, '-- (none)') || E'\n\n'
        || E'-- ── rules (decision tables; first match wins) ──\n' || coalesce(v_rules, '-- (none)') || E'\n\n'
        || E'-- ── operators (kit-scoped) ──\n' || coalesce(v_ops, '-- (none)') || E'\n\n'
        || E'-- ── metric_defs (reserved: definitions bound to kit canonical views) ──\n-- (none)\n\n'
        || E'-- ── cube_defs (reserved) ──\n-- (none)\n';

    RETURN v_out;
END
$ek$;
