-- 0169: opt-in role gating (KIT_PLATES_PLAN §20).
--
-- Default posture: roles don't exist for you. Plates render for everyone,
-- actions run for everyone, and the connection user's GRANTs remain the
-- real allow/deny (DBA territory). Three orthogonal OPT-IN layers:
--   1. set_plate_role(plate, role)   — protect a surface (render wall +
--      shelf lock; affordance over the GRANT wall, like action roles)
--   2. actions' requires_role        — protect a write (shipped in 0168-era)
--   3. grant_kit(kit, role, level)   — the GRANT choreography as one call:
--      create role if absent, USAGE on kit schemas, SELECT (read) or full
--      DML + sequence usage (write) on everything in them.
-- Kit objects are otherwise owned by whoever ran setup — nothing to DO on
-- day 1, guardrails when wanted.

ALTER TABLE rvbbit.plates ADD COLUMN IF NOT EXISTS requires_role text;

CREATE OR REPLACE FUNCTION rvbbit.set_plate_role(p_plate_id text, p_role text)
RETURNS void
LANGUAGE plpgsql
AS $spr$
BEGIN
    UPDATE rvbbit.plates
    SET requires_role = nullif(btrim(coalesce(p_role, '')), ''),
        updated_at = clock_timestamp()
    WHERE plate_id = p_plate_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'set_plate_role: no plate %', p_plate_id;
    END IF;
END
$spr$;

-- One-call guardrails: open a kit's schemas to a role. Schemas come from the
-- kit's setup_sql (CREATE SCHEMA / schema-qualified CREATE TABLE) — the same
-- honest parse remove_kit reports with. Level 'read' = USAGE + SELECT;
-- 'write' = read plus INSERT/UPDATE/DELETE and sequence usage (identity
-- columns need it). Existing objects only; rerun after kit upgrades.
CREATE OR REPLACE FUNCTION rvbbit.grant_kit(
    p_kit text,
    p_role text,
    p_level text DEFAULT 'read'
) RETURNS TABLE (granted text)
LANGUAGE plpgsql
AS $gk$
DECLARE
    k rvbbit.kits%ROWTYPE;
    v_schemas text[] := '{}';
    m text[];
    s text;
BEGIN
    IF p_level NOT IN ('read', 'write') THEN
        RAISE EXCEPTION 'grant_kit: level must be read or write';
    END IF;
    SELECT * INTO k FROM rvbbit.kits WHERE kit = p_kit;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'grant_kit: no kit named %', p_kit;
    END IF;

    BEGIN
        EXECUTE format('CREATE ROLE %I', p_role);
        granted := 'role ' || p_role || ' created';
        RETURN NEXT;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;

    IF k.setup_sql IS NOT NULL THEN
        FOR m IN SELECT regexp_matches(k.setup_sql, 'CREATE\s+SCHEMA\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-zA-Z_][\w]*)', 'gi') LOOP
            v_schemas := array_append(v_schemas, m[1]);
        END LOOP;
        FOR m IN SELECT regexp_matches(k.setup_sql, 'CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-zA-Z_][\w]*)\.', 'gi') LOOP
            v_schemas := array_append(v_schemas, m[1]);
        END LOOP;
    END IF;
    SELECT array_agg(DISTINCT x) INTO v_schemas
    FROM unnest(v_schemas) x
    WHERE EXISTS (SELECT 1 FROM pg_namespace n WHERE n.nspname = x);

    IF v_schemas IS NULL OR array_length(v_schemas, 1) IS NULL THEN
        granted := 'no kit schemas found in setup_sql — nothing to grant (grant manually if the kit uses shared schemas)';
        RETURN NEXT;
        RETURN;
    END IF;

    FOREACH s IN ARRAY v_schemas LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', s, p_role);
        IF p_level = 'read' THEN
            EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO %I', s, p_role);
            granted := format('read on schema %s → %s', s, p_role);
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO %I', s, p_role);
            EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I', s, p_role);
            granted := format('write on schema %s → %s', s, p_role);
        END IF;
        RETURN NEXT;
    END LOOP;
END
$gk$;

-- export_kit v5: opt-in plate roles travel with the kit.
CREATE OR REPLACE FUNCTION rvbbit.export_kit(p_kit text)
RETURNS text
LANGUAGE plpgsql
AS $ek$
DECLARE
    k rvbbit.kits%ROWTYPE;
    v_out text;
    v_plates text;
    v_modules text;
    v_contracts text;
    v_rules text;
    v_rule_sets text;
    v_ops text;
    v_roles text;
BEGIN
    SELECT * INTO k FROM rvbbit.kits WHERE kit = p_kit;
    IF NOT FOUND THEN
        IF NOT EXISTS (SELECT 1 FROM rvbbit.plates WHERE kit = p_kit) THEN
            RAISE EXCEPTION 'export_kit: no kit named %', p_kit;
        END IF;
        k.kit := p_kit;
        k.version := '0.0.0';
        k.title := p_kit;
        k.description := NULL;
        k.setup_sql := NULL;
    END IF;

    v_out := format(E'-- rvbbit kit: %s v%s\n-- generated by rvbbit.export_kit() · api rvbbit.kit/v1\n-- Install: run this whole file in ONE transaction (validate with ROLLBACK first).\n\n',
                    k.kit, k.version);

    IF k.requires IS NOT NULL AND k.requires <> '{}'::jsonb THEN
        v_out := v_out || E'-- ── preflight (fails with a human sentence before touching anything) ──\n'
              || format(E'SELECT rvbbit.kit_preflight_assert(%s::jsonb);\n\n',
                        rvbbit._kit_dq(k.requires::text, 'kreq'));
    END IF;

    v_out := v_out || format(E'SELECT rvbbit.upsert_kit(%L, %L, %s, %s, %L, %s::jsonb);\n\n',
        k.kit, k.title,
        CASE WHEN k.description IS NULL THEN 'NULL' ELSE quote_literal(k.description) END,
        CASE WHEN k.setup_sql IS NULL THEN 'NULL' ELSE rvbbit._kit_dq(k.setup_sql, 'ksetup') END,
        k.version,
        rvbbit._kit_dq(coalesce(k.requires, '{}'::jsonb)::text, 'kreq2'));

    IF k.setup_sql IS NOT NULL THEN
        v_out := v_out || E'-- ── setup (kit-owned schemas/tables/views/roles) ──\n'
              || k.setup_sql || E'\n\n';
    END IF;

    SELECT string_agg(
        format(E'SELECT rvbbit.upsert_plate(%L, %L, %s, %s::jsonb, %s::jsonb, %s::jsonb, %L, %s, %s);',
            p.plate_id, p.title,
            rvbbit._kit_dq(p.template, 'ktpl'),
            rvbbit._kit_dq(p.queries::text, 'kq'),
            rvbbit._kit_dq(p.actions::text, 'ka'),
            rvbbit._kit_dq(p.params::text, 'kp'),
            p.kit,
            CASE WHEN p.description IS NULL THEN 'NULL' ELSE quote_literal(p.description) END,
            p.template_version),
        E'\n' ORDER BY p.plate_id)
    INTO v_plates
    FROM rvbbit.plates p WHERE p.kit = p_kit;

    SELECT string_agg(
        format('UPDATE rvbbit.plates SET module = %L WHERE plate_id = %L;', p.module, p.plate_id),
        E'\n' ORDER BY p.plate_id)
    INTO v_modules
    FROM rvbbit.plates p WHERE p.kit = p_kit AND p.module IS NOT NULL;

    SELECT string_agg(
        format('SELECT rvbbit.set_plate_role(%L, %L);', p.plate_id, p.requires_role),
        E'\n' ORDER BY p.plate_id)
    INTO v_roles
    FROM rvbbit.plates p WHERE p.kit = p_kit AND p.requires_role IS NOT NULL;

    SELECT string_agg(
        format('SELECT rvbbit.upsert_kit_contract(%L, %L, %L, %s, %s);',
            c.kit, c.module, c.contract_id,
            rvbbit._kit_dq(c.violations_sql, 'kv'),
            CASE WHEN c.description IS NULL THEN 'NULL' ELSE quote_literal(c.description) END),
        E'\n' ORDER BY c.module, c.contract_id)
    INTO v_contracts
    FROM rvbbit.kit_contracts c WHERE c.kit = p_kit;

    SELECT string_agg(
        format('SELECT rvbbit.upsert_kit_rule(%L, %L, %L, %s, %s::jsonb, %s, %s);',
            r.kit, r.rule_set, r.rule_id,
            rvbbit._kit_dq(r.when_sql, 'kw'),
            rvbbit._kit_dq(r.verdict::text, 'kvj'),
            r.priority,
            CASE WHEN r.description IS NULL THEN 'NULL' ELSE quote_literal(r.description) END),
        E'\n' ORDER BY r.rule_set, r.priority, r.rule_id)
    INTO v_rules
    FROM rvbbit.kit_rules r WHERE r.kit = p_kit AND r.active;

    SELECT string_agg(
        format('SELECT rvbbit.upsert_kit_rule_set(%L, %L, %s, %s);',
            rs.kit, rs.rule_set,
            rvbbit._kit_dq(rs.subject_sql, 'krs'),
            CASE WHEN rs.description IS NULL THEN 'NULL' ELSE quote_literal(rs.description) END),
        E'\n' ORDER BY rs.rule_set)
    INTO v_rule_sets
    FROM rvbbit.kit_rule_sets rs WHERE rs.kit = p_kit;

    SELECT string_agg(
        format(E'DELETE FROM rvbbit.operators WHERE name = %L;\nINSERT INTO rvbbit.operators SELECT * FROM jsonb_populate_record(NULL::rvbbit.operators, %s::jsonb);',
            o.name,
            rvbbit._kit_dq(to_jsonb(o)::text, 'kop')),
        E'\n' ORDER BY o.name)
    INTO v_ops
    FROM rvbbit.operators o WHERE o.kit = p_kit;

    v_out := v_out
        || E'-- ── plates ──\n' || coalesce(v_plates, '-- (none)') || E'\n\n'
        || E'-- ── module assignments ──\n' || coalesce(v_modules, '-- (none)') || E'\n\n'
        || E'-- ── plate roles (opt-in surface gating) ──\n' || coalesce(v_roles, '-- (none)') || E'\n\n'
        || E'-- ── contracts (empty result = green) ──\n' || coalesce(v_contracts, '-- (none)') || E'\n\n'
        || E'-- ── rules (decision tables; first match wins) ──\n' || coalesce(v_rules, '-- (none)') || E'\n\n'
        || E'-- ── rule sets (subject registrations for live observability) ──\n' || coalesce(v_rule_sets, '-- (none)') || E'\n\n'
        || E'-- ── operators (kit-scoped) ──\n' || coalesce(v_ops, '-- (none)') || E'\n\n'
        || E'-- ── metric_defs (reserved: definitions bound to kit canonical views) ──\n-- (none)\n\n'
        || E'-- ── cube_defs (reserved) ──\n-- (none)\n\n'
        || format(E'-- After COMMIT, self-test the arrival:\n--   SELECT * FROM rvbbit.validate_kit(%L) WHERE NOT ok;\n', k.kit);

    RETURN v_out;
END
$ek$;
