#!/usr/bin/env python3
"""Regenerate the Warehouse-MCP tool corpus for the capability KG.

Statically extracts every `mcp.tool(name=...)` registration from
services/warehouse-mcp/server.py, resolves it to its `tool_*` implementation's
docstring, and emits SQL INSERTs for rvbbit.capability_mcp_tools (consumed by
rvbbit.capability_crawl(), migration 0147). Run after adding/changing MCP
tools, paste the block into the migration (or apply directly), then re-crawl.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
SERVER = HERE / "services" / "warehouse-mcp" / "server.py"


def main() -> int:
    src = SERVER.read_text(encoding="utf-8")
    tree = ast.parse(src)
    docs: dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("tool_"):
            doc = ast.get_docstring(node) or ""
            docs[node.name] = " ".join(doc.split())

    # Each registration owns the text up to the next registration; find the
    # first tool_* reference anywhere in that span (lambda shapes vary).
    starts = [(m.start(), m.group(1)) for m in re.finditer(r'mcp\.tool\(name="(\w+)"\)', src)]
    pairs: list[tuple[str, str]] = []
    seen: set[str] = set()
    for i, (pos, name) in enumerate(starts):
        if name in seen:
            continue
        seen.add(name)
        end = starts[i + 1][0] if i + 1 < len(starts) else pos + 2000
        span = src[pos:end]
        fn = re.search(r'\b(tool_\w+)\(', span)
        pairs.append((name, docs.get(fn.group(1), "") if fn else ""))

    def q(s: str) -> str:
        return s.replace("'", "''")

    print("-- generated by scripts/gen_capability_mcp_tools.py — do not hand-edit rows")
    print("CREATE TABLE IF NOT EXISTS rvbbit.capability_mcp_tools (")
    print("    name    text PRIMARY KEY,")
    print("    summary text NOT NULL DEFAULT ''")
    print(");")
    print("INSERT INTO rvbbit.capability_mcp_tools (name, summary) VALUES")
    rows = ",\n".join(f"('{q(n)}', '{q(d[:600])}')" for n, d in sorted(pairs))
    print(rows)
    print("ON CONFLICT (name) DO UPDATE SET summary = EXCLUDED.summary;")
    print(f"-- {len(pairs)} tools", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
